version: "3.9"
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"  # Expose port 8000
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
